/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 52b9fd2f8397837932aca1098ba74013)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	DEMO_MODE: "true";
	AWS_REGION: "us-east-1";
	BEDROCK_MODEL_ID: "us.amazon.nova-2-lite-v1:0";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEMO_MODE" | "AWS_REGION" | "BEDROCK_MODEL_ID">> {}
}
