/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 816977c5687fd5df12baa9cfe7a261e8)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	DEMO_MODE: "false";
	OPENAI_MODEL: "gpt-5.4-mini";
	OPENAI_REASONING_EFFORT: "low";
	OPENAI_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEMO_MODE" | "OPENAI_MODEL" | "OPENAI_REASONING_EFFORT" | "OPENAI_API_KEY">> {}
}
